name: 'Label approved'
description: 'Label approved merge requests'
inputs:
  githubToken: 
    description: 'GitHub token used for authentication'
    required: true
# outputs:
#   time: # output will be available to future steps
#     description: 'The current time after waiting'
runs:
  using: 'node12'
  main: 'dist/index.js'
