name: 'Label approved'
description: 'Label approved merge requests'
inputs:
  myToken: 
    description: 'GitHub token used for authentication'
    required: true
  labelerTrigger:
    description: 'Run labeler module'
    required: false
    default: false
  labelerApproves:
    description: 'Number of approves required to label a Pull Request (Labeler module)'
    required: false
    default: 2
  codeCoverageTrigger:
    description: 'Run code coverage module'
    required: false
    default: false
# outputs:
#   time: # output will be available to future steps
#     description: 'The current time after waiting'
runs:
  using: 'node12'
  main: 'dist/index.js'
